# permissions for end users to edit volumesdemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: volumesdemo-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: demovolumeoperator
    app.kubernetes.io/part-of: demovolumeoperator
    app.kubernetes.io/managed-by: kustomize
  name: volumesdemo-editor-role
rules:
- apiGroups:
  - newdemo.volume.io
  resources:
  - volumesdemoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - newdemo.volume.io
  resources:
  - volumesdemoes/status
  verbs:
  - get
